on: pull_request

jobs:
  package_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: sh ./check_packages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}