on: push

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: python3 check_packages.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}