on: push

jobs:
  package_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: sh ./check_packages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}